# ============================================
# CONFIGURAÇÃO DO BANCO DE DADOS
# USANDO VARIÁVEIS DE AMBIENTE
# ============================================

spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.msgwqxmwwlceebndvqfm&password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

