spring.application.name=Apllicattion

# ============================================
# CONFIGURAÇÃO DO BANCO DE DADOS
# ============================================

# URL com placeholders para variáveis de ambiente
spring.datasource.url=jdbc:postgresql://db.msgwqxmwwlceebndvqfm.supabase.co:5432/postgres?user=postgres&password=%25C2H%2Aav%5EeMe
spring.datasource.driver-class-name=org.postgresql.Driver

